name: meem_base_build
description: A code generator my MeeM.
version: 1.0.0
repository: https://github.com/Meemsoossaas/meem_base_build

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^6.8.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  meta: ^1.16.0
  source_gen: ^1.5.0
  build: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
